### ISSUE TITLE
nuscenes dataset loading error "assert hasattr(self.dataset, "flag") AssertionError"

### ISSUE THREAD

**Issue by taoyanzhuce001** [qcraftai/pillar-motion#14]
First, prepared the data using "data/v1.0-mini" for test.
`python tools/create_data nuscenes_data_prep --root_path /path/to/nuscenes`.
Got files:
`train_anno = "data/nuscenes/results/infos_train_05sweeps_twoframe_withcam.pkl"
val_anno = "data/nuscenes/results/infos_val_05sweeps_twoframe_withcam.pkl"
test_anno = "data/nuscenes/results/infos_test_05sweeps_twoframe_withcam.pkl"
`
But, when I run train.py, following error occured.
`Traceback (most recent call last):
  File "./tools/train.py", line 133, in <module>
    main()
  File "./tools/train.py", line 122, in main
    train_detector(
  File "/nfs/private/01_Code/pillar-motion/motion/torchie/apis/train.py", line 258, in train_detector
    data_loaders = [
  File "/nfs/private/01_Code/pillar-motion/motion/torchie/apis/train.py", line 259, in <listcomp>    build_dataloader(
  File "/nfs/private/01_Code/pillar-motion/motion/datasets/loader/build_loader.py", line 34, in build_dataloader
    sampler = DistributedGroupSampler(dataset, batch_size, world_size, rank)
  File "/nfs/private/01_Code/pillar-motion/motion/datasets/loader/sampler.py", line 166, in __init__
    assert hasattr(self.dataset, "flag")
AssertionError`

How can I solve this? THANKS!

**Comment by jonyzhang2023** [comment]
Hi can you tell me how you install the 'correlation_package' cause when I prepared the data it comes.
Can I add your wechat or something?

**Comment by taoyanzhuce001** [comment]
I copy this from PWCnet or Flownet2-pytorch.

**Comment by jonyzhang2023** [comment]
> Flownet2-pytorch.
could you tell me your env about python? I use flownet2-pytorch but still not work.

**Comment by jonyzhang2023** [comment]
![image](https://user-images.githubusercontent.com/50441823/177552487-2c89e4a5-3b07-46ea-9722-3be81567049b.png)
I have install as flownet2-pytorch. 
my python version is 3.6 , torch is 1.10.2

**Comment by taoyanzhuce001** [comment]
> ![image](https://user-images.githubusercontent.com/50441823/177552487-2c89e4a5-3b07-46ea-9722-3be81567049b.png) I have install as flownet2-pytorch. my python version is 3.6 , torch is 1.10.2

Not sure I installed the proper version. Didn't get the correct result yet... But you can try with the following version. 
correlation-cuda          0.0.0                    pypi_0    pypi
correlation-package       1.0                      pypi_0    pypi
cudatoolkit               10.1.243             h6bb024c_0 
open3d-python             0.3.0.0                  pypi_0    pypi
opencv-contrib-python     4.6.0.66                 pypi_0    pypi
opencv-python             4.6.0.66                 pypi_0    pypi
opencv-python-headless    4.6.0.66                 pypi_0    pypi 
python                    3.8.13               h12debd9_0  
torch                     1.7.1+cu101              pypi_0    pypi
torch-optimizer           0.3.0                    pypi_0    pypi
torchaudio                0.7.2                    pypi_0    pypi
torchfile                 0.1.0                    pypi_0    pypi
torchvision               0.8.2+cu101              pypi_0    pypi\
spconv                    2.1.22                   pypi_0    pypi

**Comment by jonyzhang2023** [comment]
correlation-package 1.0 pypi_0 pypi

how you install this? I only have "correlation-cuda 0.0.0 pypi_0 pypi" but donot have "correlation-package 1.0 pypi_0 pypi".. 
with installing as flownet2-pytorch said.

**Comment by STARK-775178** [comment]
> correlation-package 1.0 pypi_0 pypi
> 
> how you install this? I only have "correlation-cuda 0.0.0 pypi_0 pypi" but donot have "correlation-package 1.0 pypi_0 pypi".. with installing as flownet2-pytorch said.

same erroe ,how can i slove this. 8(
